name: Build and Push Docker Image

# Trigger workflow on push to the main, dev and staging branch
on:
  push:
    branches: ["main", "dev", "staging"]

jobs:
  #defining dev job to trigger when we push to the dev branch
  dev:
    if: github.ref == 'refs/heads/dev' #condition to check and trigger job when push to dev branch
    runs-on: ubuntu-latest  #use the latest image of ubuntu
    
    steps:
      - name: Checkout repository   #checkout to the code repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub    #Login to dockerhub using the username and passwd
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image    #Run docker command to build image with tag dev
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-simple:dev .

      - name: Push Docker image   #Pushing docker image to the dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-simple:dev

  #defining dev job to trigger when we push to the staging branch
  staging:
    if: github.ref == 'refs/heads/staging'  #condition to check and trigger job when push to staging branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub     #Login to dockerhub using the username and passwd
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image    #Run docker command to build image with tag staging
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-simple:staging .

      - name: Push Docker image   #Pushing docker image to the dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-simple:staging

  #defining dev job to trigger when we push to the main branch
  production:
    if: github.ref == 'refs/heads/main' #condition to check and trigger job when push to main branch
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub     #Login to dockerhub using the username and passwd
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker image    #Run docker command to build image with tag latest
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/react-simple:latest .

      - name: Push Docker image   #Pushing docker image to the dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/react-simple:latest
